#cargo-features = ["codegen-backend"]

[package]
name        = "faire-todo-app"
version = "0.0.15"
description = "Faire Todo App"
authors     = ["Charles Schaefer"]
edition     = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name       = "faire_todo_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri                     = { version = "2", features = ["tray-icon", "image-png", "devtools"] }
serde                     = { version = "1", features = ["derive"] }
serde_json                = { version = "1", features = ["std"] }
mdns-sd                   = "0.13"
hostname                  = "0.4.0"
local-ip-addr             = "0.1.1"
hyper                     = { version = "1.4.1", features = ["full"] }
http-body-util            = "0.1.2"
hyper-util                = { version = "0.1.7", features = ["full"] }
tokio                     = { version = "1.39.2", features = ["rt-multi-thread", "net", "sync"] } #"full"] }
bytes                     = { version = "1.7.1", default-features = false }
lazy_static               = "1.5.0"
chrono                    = { version = "0.4.38", features = ["now"] }
tauri-plugin-notification = "2"
tauri-plugin-http         = "2"
tauri-plugin-sharetarget  = "0.1.6"
tauri-plugin-shell        = "2"
tauri-plugin-deep-link    = "2"
tauri-plugin-os = "2"



[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
#codegen-backend = "cranelift"
