[package]
name = "faire-todo-app"
version = "0.0.3"
description = "Faire Todo App"
authors = ["Charles Schaefer"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "faire_todo_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = ["tray-icon", "image-png", "devtools"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-notification = "2.0.0-rc.0"
mdns-sd = "0.11.1"
hostname = "0.4.0"
tiny_http = "0.12.0"
local-ip-addr = "0.1.1"


